pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
stage('Deliver') {
    steps {
        script {
            // Ange sökvägen till JAR-filen baserat på Maven-utgången
            def JAR_PATH = "target/my-app-1.0-SNAPSHOT.jar"

            // Kolla om JAR-filen finns på den angivna sökvägen
            if (!fileExists(JAR_PATH)) {
                error "Error: JAR file not found at $JAR_PATH. Please check the path."
            }

            // Kör ditt leveransskript
            sh "./jenkins/scripts/deliver.sh"
        }
    }
}

}
